import type { Category } from '@/lib/types'

const items = (paths: string[], alt: string) => paths.map((src) => ({ src, alt }))
const w = (name: string) => `/Website/${name}`

/**
 * Website photo → category mapping (visual review).
 * Primary rule: one accurate home for each shot; hero = best staged lifestyle frame.
 */
export const FALLBACK_CATEGORIES: Category[] = [
  {
    title: 'Sofas & Loveseats',
    navLabel: 'Sofas',
    slug: 'loveseats',
    subtitle: 'Sofa and loveseat pairings for living rooms that gather.',
    heroImage: w('IMG_4540.PNG'),
    menuImage: w('IMG_4581.PNG'),
    order: 1,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4540.PNG'),
        w('IMG_4581.PNG'),
        w('IMG_4543.PNG'),
        w('IMG_4547.PNG'),
        w('IMG_4212.PNG'),
        w('IMG_4386.PNG'),
        w('IMG_4387.PNG'),
        '/products/loveseat (9).jpeg',
        '/products/loveseat (7).jpeg',
        '/products/loveseat (2).jpeg',
      ],
      'Sofas & Loveseats'
    ),
  },
  {
    title: 'Bedroom Sets',
    navLabel: 'Bedroom',
    slug: 'bedroom-sets',
    subtitle: 'Complete bedroom suites — statement headboards, nightstands, and soft light.',
    heroImage: w('IMG_4365.PNG'),
    menuImage: w('IMG_4337.PNG'),
    order: 2,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4365.PNG'),
        w('IMG_4337.PNG'),
        w('IMG_4590.PNG'),
        w('IMG_4635.PNG'),
        w('IMG_4589.PNG'),
        w('IMG_4593.PNG'),
        w('IMG_4501.PNG'),
        w('IMG_4502.PNG'),
        w('IMG_4503.PNG'),
        w('IMG_4494.PNG'),
        w('IMG_4495.PNG'),
        w('IMG_4497.PNG'),
        w('IMG_4499.PNG'),
        w('IMG_4583.PNG'),
        w('IMG_4584.PNG'),
        w('IMG_4588.PNG'),
        w('IMG_4592.PNG'),
        w('IMG_4594.PNG'),
        w('IMG_4596.PNG'),
        w('IMG_4636.PNG'),
        w('IMG_4637.PNG'),
        w('IMG_4638.PNG'),
        w('IMG_4639.PNG'),
        w('IMG_4363.PNG'),
        w('IMG_4364.PNG'),
        w('IMG_4338.PNG'),
        w('IMG_4339.PNG'),
        w('IMG_4340.PNG'),
        w('IMG_4344.PNG'),
        w('IMG_4345.PNG'),
        w('IMG_4126.PNG'),
        w('IMG_4127.PNG'),
        w('IMG_4106.PNG'),
        w('IMG_4190.PNG'),
        w('IMG_4191.PNG'),
        w('IMG_4192.PNG'),
        w('IMG_4194.PNG'),
        w('IMG_4195.PNG'),
        w('IMG_4196.PNG'),
        w('IMG_4213.PNG'),
        w('IMG_4215.PNG'),
        w('IMG_4496.PNG'),
        w('IMG_4198.PNG'),
        w('IMG_4200.PNG'),
        w('IMG_4100.PNG'),
        w('24CCAB52-B598-4F49-AC64-B76523BA9CD6.jpg'),
      ],
      'Bedroom Set'
    ),
  },
  {
    title: 'Dining Tables',
    navLabel: 'Dining',
    slug: 'dining-tables',
    subtitle: 'Dining tables and chairs for everyday meals and evening company.',
    heroImage: w('IMG_4657.PNG'),
    menuImage: w('IMG_4654.PNG'),
    order: 3,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4657.PNG'),
        w('IMG_4654.PNG'),
        w('IMG_4206.PNG'),
        w('IMG_4652.PNG'),
        w('IMG_4653.PNG'),
        w('IMG_4656.PNG'),
        w('IMG_4659.PNG'),
        w('IMG_4660.PNG'),
        w('IMG_4661.PNG'),
        w('IMG_4658.PNG'),
        w('IMG_4216.PNG'),
      ],
      'Dining Table'
    ),
  },
  {
    title: 'Leather Sectionals',
    navLabel: 'Leather',
    slug: 'leather-sectionals',
    subtitle: 'Leather and leatherette sectionals with a polished, lasting presence.',
    heroImage: w('IMG_4390.PNG'),
    menuImage: w('IMG_4390.PNG'),
    order: 4,
    showInNav: true,
    gallery: items(
      [w('IMG_4390.PNG'), '/products/custom-furniture/custom-new (22).jpeg'],
      'Leather Sectional'
    ),
  },
  {
    title: 'Fabric Selections',
    navLabel: 'Fabric Selections',
    slug: 'fabric-sectionals',
    subtitle: 'Fabric sectionals and modular seating for lived-in living rooms.',
    heroImage: w('IMG_4546.PNG'),
    menuImage: w('IMG_4549.PNG'),
    order: 5,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4546.PNG'),
        w('IMG_4549.PNG'),
        w('IMG_4542.PNG'),
        w('IMG_4544.PNG'),
        w('IMG_4545.PNG'),
        w('IMG_4158.PNG'),
        w('IMG_4209.PNG'),
        w('IMG_4211.PNG'),
        w('IMG_4247.PNG'),
        w('IMG_4384.PNG'),
        w('IMG_4580.PNG'),
        w('IMG_4389.PNG'),
        w('IMG_4391.PNG'),
        w('IMG_4394.PNG'),
        w('IMG_4385.PNG'),
        w('IMG_4388.PNG'),
        w('IMG_4548.PNG'),
        w('IMG_4579.PNG'),
        w('IMG_4379.PNG'),
        w('IMG_4382.PNG'),
        w('IMG_4393.PNG'),
        w('c24c034d-054e-42bc-93ba-44ecccc39b95.jpg'),
      ],
      'Fabric Sectional'
    ),
  },
  {
    title: 'Mattresses',
    navLabel: 'Mattresses',
    slug: 'mattresses',
    subtitle: 'Supportive mattresses from trusted brands — ready for a better night’s sleep.',
    heroImage: '/products/mattress-18.jpeg',
    menuImage: '/products/mattress.jpeg',
    order: 6,
    showInNav: true,
    gallery: items(
      [
        '/products/mattress-18.jpeg',
        '/products/mattress.jpeg',
        w('IMG_4337.PNG'),
        w('IMG_4339.PNG'),
        w('IMG_4100.PNG'),
      ],
      'Mattress'
    ),
  },
  {
    title: 'Vanities',
    navLabel: 'Vanities',
    slug: 'vanities',
    subtitle: 'Hollywood vanities and lit mirrors for a morning ritual that feels elevated.',
    heroImage: w('IMG_4335.PNG'),
    menuImage: w('IMG_4102.PNG'),
    order: 7,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4335.PNG'),
        w('IMG_4336.PNG'),
        w('IMG_4343.PNG'),
        w('IMG_4102.PNG'),
      ],
      'Vanity'
    ),
  },
  {
    title: 'Bunk Beds',
    navLabel: 'Bunk Beds',
    slug: 'bunk-beds',
    subtitle: 'Bunks, lofts, and space-smart sleepers for shared rooms.',
    heroImage: w('IMG_4296.PNG'),
    menuImage: w('IMG_4300.PNG'),
    order: 8,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4296.PNG'),
        w('IMG_4300.PNG'),
        w('IMG_4302.PNG'),
        w('IMG_4306.PNG'),
        w('IMG_4319.PNG'),
        w('IMG_4304.PNG'),
        w('IMG_4305.PNG'),
        w('IMG_4307.PNG'),
        '/products/bunk-bed.jpeg',
      ],
      'Bunk Bed'
    ),
  },
  {
    title: 'Custom Furniture',
    navLabel: 'Custom',
    slug: 'custom-furniture',
    subtitle: 'Built-to-order pieces shaped to your room, fabric, and how you live.',
    // Signature custom multi-bunk / built systems + showroom custom catalog
    heroImage: w('IMG_4296.PNG'),
    menuImage: '/products/custom-furniture/custom-new (1).jpeg',
    order: 9,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4296.PNG'),
        '/products/custom-furniture/custom-new (1).jpeg',
        '/products/custom-furniture/custom-new (12).jpeg',
        '/products/custom-furniture/custom-new (16).jpeg',
        '/products/custom-furniture/custom-new (28).jpeg',
        '/products/custom-furniture/custom-new (18).jpeg',
        '/products/custom-furniture/custom-new (40).jpeg',
        '/products/custom-furniture/custom-new (48).jpeg',
        '/products/custom-furniture/custom-new (22).jpeg',
      ],
      'Custom Furniture'
    ),
  },
]
