import type { Category } from '@/lib/types'

const items = (paths: string[], alt: string) => paths.map((src) => ({ src, alt }))
const w = (name: string) => `/Website/${name}`

export const FALLBACK_CATEGORIES: Category[] = [
  {
    title: 'Sofas & Loveseats',
    navLabel: 'Sofas',
    slug: 'loveseats',
    subtitle: 'Deep seating and tailored silhouettes for rooms meant to gather.',
    heroImage: w('IMG_4540.PNG'),
    menuImage: w('IMG_4580.PNG'),
    order: 1,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4540.PNG'),
        w('IMG_4580.PNG'),
        w('IMG_4542.PNG'),
        w('IMG_4158.PNG'),
        w('IMG_4579.PNG'),
        w('IMG_4211.PNG'),
        '/products/loveseat (9).jpeg',
        '/products/loveseat (7).jpeg',
      ],
      'Sofas & Loveseats'
    ),
  },
  {
    title: 'Bedroom Sets',
    navLabel: 'Bedroom',
    slug: 'bedroom-sets',
    subtitle: 'Statement headboards, soft light, and complete suites for restful nights.',
    heroImage: w('IMG_4500.PNG'),
    menuImage: w('IMG_4365.PNG'),
    order: 2,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4500.PNG'),
        w('IMG_4365.PNG'),
        w('IMG_4498.PNG'),
        w('IMG_4590.PNG'),
        w('IMG_4635.PNG'),
        w('IMG_4589.PNG'),
        w('IMG_4192.PNG'),
        w('IMG_4494.PNG'),
        w('IMG_4593.PNG'),
        w('IMG_4126.PNG'),
        w('IMG_4106.PNG'),
        w('IMG_4496.PNG'),
        w('IMG_4584.PNG'),
        w('IMG_4503.PNG'),
        w('IMG_4363.PNG'),
        w('IMG_4200.PNG'),
        w('IMG_4190.PNG'),
        w('IMG_4194.PNG'),
      ],
      'Bedroom Set'
    ),
  },
  {
    title: 'Dining Tables',
    navLabel: 'Dining',
    slug: 'dining-tables',
    subtitle: 'Tables and seating sized for everyday meals and evening company.',
    heroImage: w('IMG_4654.PNG'),
    menuImage: w('IMG_4657.PNG'),
    order: 3,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4654.PNG'),
        w('IMG_4657.PNG'),
        w('IMG_4206.PNG'),
        w('IMG_4652.PNG'),
        w('IMG_4661.PNG'),
        w('IMG_4659.PNG'),
        w('IMG_4653.PNG'),
        w('IMG_4656.PNG'),
        w('IMG_4658.PNG'),
        w('IMG_4660.PNG'),
      ],
      'Dining Table'
    ),
  },
  {
    title: 'Leather Sectionals',
    navLabel: 'Leather',
    slug: 'leather-sectionals',
    subtitle: 'Rich leather sectionals with a polished, lasting presence.',
    heroImage: w('IMG_4390.PNG'),
    menuImage: w('IMG_4390.PNG'),
    order: 4,
    showInNav: true,
    gallery: items(
      [w('IMG_4390.PNG'), '/products/custom-furniture/custom-new (22).jpeg'],
      'Leather Sectional'
    ),
  },
  {
    title: 'Fabric Selections',
    navLabel: 'Fabric Selections',
    slug: 'fabric-sectionals',
    subtitle: 'Soft textiles and modular shapes for lived-in living rooms.',
    heroImage: w('IMG_4546.PNG'),
    menuImage: w('IMG_4549.PNG'),
    order: 5,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4546.PNG'),
        w('IMG_4549.PNG'),
        w('IMG_4542.PNG'),
        w('IMG_4158.PNG'),
        w('IMG_4540.PNG'),
        w('IMG_4580.PNG'),
        w('IMG_4579.PNG'),
        w('IMG_4211.PNG'),
        w('IMG_4389.PNG'),
        w('IMG_4247.PNG'),
        w('IMG_4384.PNG'),
        w('IMG_4394.PNG'),
        w('IMG_4388.PNG'),
        w('IMG_4385.PNG'),
        w('IMG_4387.PNG'),
        w('c24c034d-054e-42bc-93ba-44ecccc39b95.jpg'),
      ],
      'Fabric Selections'
    ),
  },
  {
    title: 'Mattresses',
    navLabel: 'Mattresses',
    slug: 'mattresses',
    subtitle: 'Supportive sleep surfaces from trusted brands, ready for tonight.',
    heroImage: '/products/mattress-18.jpeg',
    menuImage: w('IMG_4100.PNG'),
    order: 6,
    showInNav: true,
    gallery: items(
      ['/products/mattress-18.jpeg', '/products/mattress.jpeg', w('IMG_4100.PNG')],
      'Mattress'
    ),
  },
  {
    title: 'Vanities',
    navLabel: 'Vanities',
    slug: 'vanities',
    subtitle: 'Lit mirrors and clean lines for a morning ritual that feels elevated.',
    heroImage: w('IMG_4335.PNG'),
    menuImage: w('IMG_4102.PNG'),
    order: 7,
    showInNav: true,
    gallery: items(
      [w('IMG_4335.PNG'), w('IMG_4102.PNG'), w('IMG_4192.PNG'), w('IMG_4589.PNG'), w('IMG_4336.PNG'), w('IMG_4337.PNG')],
      'Vanity'
    ),
  },
  {
    title: 'Bunk Beds',
    navLabel: 'Bunk Beds',
    slug: 'bunk-beds',
    subtitle: 'Space-smart bunks and loft beds built for shared rooms that still feel special.',
    heroImage: w('IMG_4296.PNG'),
    menuImage: w('IMG_4300.PNG'),
    order: 8,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4296.PNG'),
        w('IMG_4300.PNG'),
        w('IMG_4319.PNG'),
        w('IMG_4302.PNG'),
        w('IMG_4304.PNG'),
        w('IMG_4306.PNG'),
        w('IMG_4307.PNG'),
        '/products/bunk-bed.jpeg',
      ],
      'Bunk Bed'
    ),
  },
  {
    title: 'Custom Furniture',
    navLabel: 'Custom',
    slug: 'custom-furniture',
    subtitle: 'Pieces shaped to your room, your fabric, and how you actually live.',
    heroImage: w('IMG_4365.PNG'),
    menuImage: w('IMG_4639.PNG'),
    order: 9,
    showInNav: true,
    gallery: items(
      [
        w('IMG_4365.PNG'),
        w('IMG_4639.PNG'),
        w('IMG_4296.PNG'),
        w('IMG_4635.PNG'),
        w('IMG_4636.PNG'),
        w('IMG_4637.PNG'),
        w('IMG_4638.PNG'),
        '/products/custom-furniture/custom-new (1).jpeg',
        '/products/custom-furniture/custom-new (12).jpeg',
        '/products/custom-furniture/custom-new (28).jpeg',
      ],
      'Custom Furniture'
    ),
  },
]
