import type { Category } from '@/lib/types'

const items = (paths: string[], alt: string) => paths.map((src) => ({ src, alt }))

export const FALLBACK_CATEGORIES: Category[] = [
  {
    title: 'Sofas & Loveseats',
    navLabel: 'Sofas',
    slug: 'loveseats',
    subtitle: 'Premium sofas and loveseats for cozy seating spaces',
    heroImage: '/products/loveseat (9).jpeg',
    menuImage: '/products/loveseat (9).jpeg',
    order: 1,
    showInNav: true,
    gallery: items(
      [
        '/products/loveseat (9).jpeg',
        '/products/loveseat (2).jpeg',
        '/products/loveseat (3).jpeg',
        '/products/loveseat (7).jpeg',
        '/products/loveseat (6).jpeg',
        '/products/loveseat (10).jpeg',
        '/products/loveseat (13).jpeg',
        '/products/loveseat (14).jpeg',
      ],
      'Sofas & Loveseats'
    ),
  },
  {
    title: 'Bedroom Sets',
    navLabel: 'Bedroom',
    slug: 'bedroom-sets',
    subtitle: 'Complete bedroom solutions for restful nights',
    heroImage: '/products/gallery/gallery (5).jpeg',
    menuImage: '/products/gallery/gallery (5).jpeg',
    order: 2,
    showInNav: true,
    gallery: items(
      [
        '/products/gallery/gallery (5).jpeg',
        '/products/custom-furniture/custom-new (28).jpeg',
        '/products/custom-furniture/custom-new (12).jpeg',
        '/products/custom-furniture/custom-new (16).jpeg',
        '/products/custom-furniture/custom-new (1).jpeg',
        '/products/mattress-18.jpeg',
      ],
      'Bedroom Set'
    ),
  },
  {
    title: 'Dining Tables',
    navLabel: 'Dining',
    slug: 'dining-tables',
    subtitle: 'Dining tables and seating for gathering spaces',
    heroImage: '/products/dinnig-table (2).jpeg',
    menuImage: '/products/dinnig-table (2).jpeg',
    order: 3,
    showInNav: true,
    gallery: items(
      [
        '/products/dinnig-table (2).jpeg',
        '/products/dinning-table (10).jpeg',
        '/products/dinnig-table (3).jpeg',
        '/products/dinnig-table (6).jpeg',
        '/products/dinnig-table (8).jpeg',
        '/products/dinnig-table (5).jpeg',
      ],
      'Dining Table'
    ),
  },
  {
    title: 'Leather Sectionals',
    navLabel: 'Leather',
    slug: 'leather-sectionals',
    subtitle: 'Premium leather sectionals for sophisticated living spaces',
    heroImage: '/products/custom-furniture/custom-new (22).jpeg',
    menuImage: '/products/custom-furniture/custom-new (22).jpeg',
    order: 4,
    showInNav: true,
    gallery: items(['/products/custom-furniture/custom-new (22).jpeg'], 'Leather Sectional'),
  },
  {
    title: 'Fabric Selections',
    navLabel: 'Fabric Selections',
    slug: 'fabric-sectionals',
    subtitle: 'Premium fabric selections for comfortable living spaces',
    heroImage: '/products/gallery/gallery (6).jpeg',
    menuImage: '/products/gallery/gallery (6).jpeg',
    order: 5,
    showInNav: true,
    gallery: items(
      [
        '/products/gallery/gallery (6).jpeg',
        '/products/custom-furniture/custom-new (18).jpeg',
        '/products/loveseat (9).jpeg',
        '/products/loveseat (7).jpeg',
      ],
      'Fabric Selections'
    ),
  },
  {
    title: 'Mattresses',
    navLabel: 'Mattresses',
    slug: 'mattresses',
    subtitle: 'Quality mattresses for restful sleep',
    heroImage: '/products/mattress-18.jpeg',
    menuImage: '/products/mattress-18.jpeg',
    order: 6,
    showInNav: true,
    gallery: items(['/products/mattress-18.jpeg', '/products/mattress.jpeg'], 'Mattress'),
  },
  {
    title: 'Vanities',
    navLabel: 'Vanities',
    slug: 'vanities',
    subtitle: 'Premium vanities for bedroom and bathroom spaces',
    heroImage: '/products/gallery/gallery (1).jpeg',
    menuImage: '/products/gallery/gallery (1).jpeg',
    order: 7,
    showInNav: true,
    gallery: items(['/products/gallery/gallery (1).jpeg'], 'Vanity'),
  },
  {
    title: 'Bunk Beds',
    navLabel: 'Bunk Beds',
    slug: 'bunk-beds',
    subtitle: 'Premium bunk beds and loft beds for every room',
    heroImage: '/products/bunk-bed.jpeg',
    menuImage: '/products/bunk-bed.jpeg',
    order: 8,
    showInNav: true,
    gallery: items(['/products/bunk-bed.jpeg'], 'Bunk Bed'),
  },
  {
    title: 'Custom Furniture',
    navLabel: 'Custom',
    slug: 'custom-furniture',
    subtitle: 'Design furniture tailored to your space and style',
    heroImage: '/products/custom-furniture/custom-new (1).jpeg',
    menuImage: '/products/custom-furniture/custom-new (1).jpeg',
    order: 9,
    showInNav: true,
    gallery: items(
      [
        '/products/custom-furniture/custom-new (1).jpeg',
        '/products/custom-furniture/custom-new (12).jpeg',
        '/products/custom-furniture/custom-new (16).jpeg',
        '/products/custom-furniture/custom-new (28).jpeg',
        '/products/custom-furniture/custom-new (18).jpeg',
        '/products/custom-furniture/custom-new (40).jpeg',
        '/products/custom-furniture/custom-new (48).jpeg',
      ],
      'Custom Furniture'
    ),
  },
]
