import { defineField, defineType } from 'sanity'

export const post = defineType({
  name: 'post',
  title: 'Journal',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'display', title: 'Display' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'kicker',
      title: 'Kicker',
      type: 'string',
      group: 'display',
      description: 'Short label above the title, e.g. Showroom Notes.',
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (rule) => rule.max(280),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt text' }],
    }),
    defineField({ name: 'coverImageUrl', title: 'Cover image URL (fallback)', type: 'string', group: 'content' }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'display',
      options: {
        list: [
          { title: 'Buying Guide', value: 'Buying Guide' },
          { title: 'Interior Tips', value: 'Interior Tips' },
          { title: 'Shopping Guide', value: 'Shopping Guide' },
          { title: 'Trends', value: 'Trends' },
          { title: 'Care & Maintenance', value: 'Care & Maintenance' },
          { title: 'Showroom', value: 'Showroom' },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'display',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'featured',
      title: 'Featured on journal',
      type: 'boolean',
      group: 'display',
      initialValue: false,
    }),
    defineField({
      name: 'published',
      title: 'Published',
      type: 'boolean',
      group: 'display',
      initialValue: true,
    }),
    defineField({ name: 'publishedAt', title: 'Published at', type: 'datetime', group: 'display' }),
    defineField({ name: 'readTime', title: 'Read time', type: 'string', group: 'display' }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
      group: 'display',
      initialValue: 'My Space Furniture',
    }),
    defineField({
      name: 'featuredQuote',
      title: 'Pull quote',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Optional highlighted quote shown on the article page.',
    }),
    defineField({
      name: 'relatedCategories',
      title: 'Related collections',
      type: 'array',
      group: 'display',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'array',
      group: 'content',
      of: [
        { type: 'block' },
        { type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', type: 'string', title: 'Alt text' }] },
      ],
    }),
    defineField({
      name: 'bodyHtml',
      title: 'Legacy HTML',
      type: 'text',
      rows: 20,
      group: 'content',
      description: 'Used for migrated posts. Prefer the Body field for new articles.',
    }),
    defineField({ name: 'seoTitle', title: 'SEO title', type: 'string', group: 'seo' }),
    defineField({ name: 'seoDescription', title: 'SEO description', type: 'text', rows: 3, group: 'seo' }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'category', media: 'coverImage', featured: 'featured' },
    prepare({ title, subtitle, media, featured }) {
      return {
        title,
        subtitle: featured ? `Featured · ${subtitle || 'Journal'}` : subtitle,
        media,
      }
    },
  },
  orderings: [
    { title: 'Published date, newest', name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Title', name: 'titleAsc', by: [{ field: 'title', direction: 'asc' }] },
  ],
})
